### PR TITLE
Fixed Bower Setup

### PR DESCRIPTION
**Pull request by acburdine**
I removed vendor files from the repository and fixed bower setup to install them correctly

### CODE REVIEW

**Comment by acburdine** [comment]
the first 3 commits were problems rebasing the fork......

**Comment by ianlopshire** [comment]
I'm not sure we should ignore the css. This should be usable upon download without needing to run any bower, npm, or gulp commands.

**Comment by acburdine** [comment]
So do you want the entire bower dependency contents put into the vendor directory? It results in a lot of files.

I'll put the CSS back in though

**Comment by acburdine** [comment]
I'm just going to close this pull request. We decided to pretty much undo all of the changes anyway

**Pull request closed without merging**
